#! /usr/bin/env python3

import rospy
import curses
from geometry_msgs.msg import Twist

def main(stdscr):
	#init curses settings
	curses.cbreak()
	stdscr.keypad(True)
	stdscr.nodelay(True)

	rospy.init_node('my_teleop_node', anonymous=True)
	pub = rospy.Publisher('/turtle1/cmd_vel', Twist, queue_size=10)

	rate = rospy.Rate(10)

	stdscr.addstr(0, 0, "Teleop Node Running!")
	stdscr.addstr(1, 0, "W: Forward | S: Backward | A: Rotate Left | D: Rotate Rigt")
	stdscr.addstr(2, 0, "Press Ctrl+C to quit")
	stdscr.refresh()

	while not rospy.is_shutdown():
		key = stdscr.getch()
		move_cmd = Twist()
		
		move_cmd.linear.x = 0.0
		move_cmd.angular.z = 0.0

		if key == ord('w'):
			move_cmd.linear.x = 2.0
			move_cmd.angular.z = 0.0
		elif key == ord('s'):
			move_cmd.linear.x = -2.0
			move_cmd.angular.z = 0.0
		elif key == ord('a'):
			move_cmd.linear.x = 0.0
			move_cmd.angular.z = 2.0
		elif key ==ord('d'):
			move_cmd.linear.x = 0.0
			move_cmd.angular.z = -2.0

		pub.publish(move_cmd)
		rate.sleep()

if __name__ == '__main__':
	try:
		curses.wrapper(main)
	except rospy.ROSInterruptException:
		pass
